#!/bin/bash
# example file to be used with --hookdir
#
# invoke shell if build fails.
apt install -y "${APTGETOPT[@]}" nano less
cd /tmp/buildd/*/debian/..
/bin/bash < /dev/tty > /dev/tty 2> /dev/tty

